
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 27 14:25:42 CST 2017
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pto = 12;
  public static final int parDer = 55;
  public static final int continuar = 9;
  public static final int bool = 26;
  public static final int dosPtos = 64;
  public static final int distinto = 34;
  public static final int corIzq = 59;
  public static final int resta = 58;
  public static final int suma = 57;
  public static final int errar = 70;
  public static final int mod = 50;
  public static final int comprobar = 15;
  public static final int retorna = 8;
  public static final int conservar = 6;
  public static final int ape = 52;
  public static final int false_ = 28;
  public static final int char_ = 27;
  public static final int ent = 66;
  public static final int coma = 56;
  public static final int mayIgual = 33;
  public static final int cie = 53;
  public static final int igual = 31;
  public static final int men = 35;
  public static final int double_ = 25;
  public static final int decre = 44;
  public static final int si = 14;
  public static final int extiende = 7;
  public static final int salir = 18;
  public static final int mientras = 20;
  public static final int circRec = 11;
  public static final int dec = 67;
  public static final int defecto = 17;
  public static final int may = 36;
  public static final int menos = 46;
  public static final int protegido = 5;
  public static final int corDer = 60;
  public static final int var = 22;
  public static final int llaveIzq = 61;
  public static final int EOF = 0;
  public static final int mas = 45;
  public static final int int_ = 24;
  public static final int menIgual = 32;
  public static final int consola = 10;
  public static final int para = 19;
  public static final int error = 1;
  public static final int publico = 3;
  public static final int true_ = 29;
  public static final int or = 40;
  public static final int pot = 49;
  public static final int parIzq = 54;
  public static final int por = 47;
  public static final int car = 68;
  public static final int id = 65;
  public static final int xor = 39;
  public static final int caso = 16;
  public static final int string_ = 30;
  public static final int hacer = 21;
  public static final int lienzo = 23;
  public static final int fin = 51;
  public static final int privado = 4;
  public static final int not = 42;
  public static final int and = 41;
  public static final int nor = 38;
  public static final int asigna = 63;
  public static final int inc = 43;
  public static final int llaveDer = 62;
  public static final int div = 48;
  public static final int principal = 2;
  public static final int nand = 37;
  public static final int cadena = 69;
  public static final int sino = 13;
  
  
 
}

